{{- range $component, $config := .Values.services }}
 {{- range $config.ports}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  labels:
    {{- include "app.labels" $config | nindent 4 }}
spec:
  selector:
    app: {{ $config.labels.app }}
  type: {{ .serviceType }}
  ports:
  - protocol: TCP
    port: {{ .port }}
    {{- if eq .serviceType "NodePort"}}
    nodePort: {{ .nodePort }}
    {{- end}}
    targetPort: {{ .targetPort }}
    name: {{ .name }}
---
  {{- end }}
{{- end }}