deployments:
  giropops-senhas:
    name: "giopops-senhas-helm"
    image: "linuxtips/giropops-senhas:1.0"
    replicas: "3"
    ports:
      - port: 5000
        targetPort: 5000
        name: "giropops-senhas-port"
        serviceType: "NodePort"
        nodePort: 32600
      - port: 8088
        targetPort: 8088
        name: "giropops-senhas-metrics"
        serviceType: "ClusterIP"
        nodePort: "banana"
    labels:
      app: "giropos-senhas"
      env: "labs"
      live: "false"
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
      requests:
        memory: "64Mi"
        cpu: "250m"
  redis:
    name: "redis-helm"
    image: "redis"
    replicas: "1"
    labels:
      app: "redis"
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
      requests:
        memory: "64Mi"
        cpu: "250m"
services:
  giropops-senhas:
    ports:
    - port: 5000
      targetPort: 5000
      name: "app"
      serviceType: "NodePort"
      nodePort: 32082
    - port: 8088
      targetPort: 8088
      name: "metrics"
      serviceType: "ClusterIP"
      nodePort: "banana"
    labels:
      app: "giropos-senhas"
      env: "labs"
      live: "false"
  redis:
    ports:
    - port: 6379
      targetPort: 6379
      name: "redis-service"
      serviceType: "ClusterIP"
    labels:
      app: "redis"
      env: "labs"
      live: "false"
observability:
  giropops-senhas:
    logging: true
    metrics:
      enabled: true
      path: "/metrics"
databases:
  giropops-senhas:
    mysql:
      host: "mysql.svc.cluster.local"
      port: 3306
      name: "MyDB"