apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.giropopsSenhas.service.name }}
  labels:
    app: {{ .Values.giropopsSenhas.labels.apps }}
spec:
  selector:
    app: {{ .Values.giropopsSenhas.labels.apps }}
  type: {{ .Values.giropopsSenhas.service.type }}
  ports:
  - protocol: TCP
    port: {{ .Values.giropopsSenhas.service.port }}
    nodePort: {{ .Values.giropopsSenhas.service.nodePort }}
    targetPort: {{ .Values.giropopsSenhas.service.targetPort }}
    name: {{ .Values.giropopsSenhas.service.namePort }}
