apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis.service.name }}
spec:
  selector:
    app: {{ .Values.redis.labels.apps }}
  type: {{ .Values.redis.service.type }}
  ports:
  - protocol: TCP
    port: {{ .Values.redis.service.port }}
    targetPort: {{ .Values.redis.targetPort }}
